# Generated by Django 2.2.3 on 2019-09-03 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JiraRole',
            fields=[
                ('jRoleId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('jProject', models.CharField(max_length=100)),
                ('jRole', models.CharField(max_length=100)),
                ('jUrl', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WarnLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录日期')),
                ('real_date', models.DateTimeField(auto_now=True, verbose_name='发生日期')),
                ('content', models.CharField(max_length=1000)),
                ('level', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='JiraUser',
            fields=[
                ('juid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('displayName', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('avatarUrl', models.CharField(max_length=512)),
                ('jRoleId', models.ManyToManyField(to='common.JiraRole')),
            ],
        ),
    ]
