# Generated by Django 2.2.3 on 2019-09-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JiraRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('jProject', models.CharField(max_length=100)),
                ('jRole', models.CharField(max_length=100)),
                ('jId', models.CharField(max_length=100)),
                ('jUrl', models.CharField(max_length=512)),
            ],
        ),
    ]
