# Generated by Django 2.2.3 on 2019-09-03 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_auto_20190903_0603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JiraRole',
        ),
    ]
